### ISSUE TITLE
Not working without the nocert label

### ISSUE THREAD

**Issue by portokallidis** [eforce21/letsencrypt-nginx-proxy#13]
Hello and Thank you for your great work!
I am facing some issues with the cert requests.
It does work as a virtual host proxy when i apply the nocert label though..
##### stackfile:

```
edu:
  environment:
    - 'NODE_ENV=production'
    - 'PORT=80'
    - 'VIRTUAL_HOST=edu.test.carre-project.eu'
  expose:
    - '80'
  image: 'carre/educational-aggregator:latest'
  labels:
    letsencrypt.nocert: 'true'
  restart: 'always'

entry:
  environment:
    - 'NODE_ENV=production'
    - 'PORT=80'
    - 'VIRTUAL_HOST=entry.test.carre-project.eu'
  expose:
    - '80'
  image: 'carre/risk-entry-system:latest'
  labels:
    letsencrypt.nocert: 'true'
  restart: 'always'

proxy:
  environment:
    - 'LETSENCRYPT_EMAIL=portokallidis@gmail.com'
  image: 'eforce21/letsencrypt-nginx-proxy:latest'
  links:
    - 'edu'
    - 'entry'
  ports:
    - '80:80'
  restart: 'always'
  volumes:
    - '/var/run/docker.sock:/tmp/docker.sock:ro'
```
##### This is my docker ps output

```
eforce21/letsencrypt-nginx-proxy:latest "/app/docker-entrypoi" 10 minutes ago Up 10 minutes 0.0.0.0:80->80/tcp, 443/tcp proxy-1.test4.09c4dcd3

carre/risk-entry-system:latest "node server.js" 10 minutes ago Up 10 minutes 80/tcp entry-1.test4.6ff9df72

carre/educational-aggregator:latest "npm start" 10 minutes ago Up 10 minutes 80/tcp edu-1.test4.ee12a5eb
```
##### LOGS

proxy-1 | 2016-06-16T20:04:47.276860204Z forego | starting nginx.1 on port 5000
proxy-1 | 2016-06-16T20:04:47.285017483Z forego | starting confgen.1 on port 5100
proxy-1 | 2016-06-16T20:04:47.294697027Z forego | starting sslgen.1 on port 5300
proxy-1 | 2016-06-16T20:04:47.306455524Z forego | starting cron.1 on port 5600
proxy-1 | 2016-06-16T20:04:47.580207350Z sslgen.1 | 2016/06/16 20:04:47 Generated '/createSSL.sh' from 3 containers
proxy-1 | 2016-06-16T20:04:47.584037007Z sslgen.1 | 2016/06/16 20:04:47 Running '/createSSL.sh'
proxy-1 | 2016-06-16T20:04:47.624114454Z confgen.1 | 2016/06/16 20:04:47 Generated '/etc/nginx/conf.d/default.conf' from 3 containers
proxy-1 | 2016-06-16T20:04:47.628955211Z confgen.1 | 2016/06/16 20:04:47 Running 'nginx -s reload'
proxy-1 | 2016-06-16T20:04:47.717094977Z confgen.1 | 2016/06/16 20:04:47 [nginx -s reload]: 2016/06/16 20:04:47 [notice] 38#38: signal process started
proxy-1 | 2016-06-16T20:04:47.770139391Z confgen.1 | 2016/06/16 20:04:47 Watching docker events
proxy-1 | 2016-06-16T20:04:47.816308666Z confgen.1 | 2016/06/16 20:04:47 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
proxy-1 | 2016-06-16T20:04:53.193949403Z nginx.1 | edu.test.carre-project.eu 66.133.109.36 - - [16/Jun/2016:20:04:53 +0000] "GET /.well-known/acme-challenge/VhrA90oV9L9xsgIraUrefpMlq3it6hChUqqOTNLLyWY HTTP/1.1" 200 87 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
proxy-1 | 2016-06-16T20:05:05.132478599Z nginx.1 | entry.test.carre-project.eu 212.251.18.83 - - [16/Jun/2016:20:05:05 +0000] "GET / HTTP/1.1" 200 742 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
proxy-1 | 2016-06-16T20:05:05.464320366Z nginx.1 | entry.test.carre-project.eu 212.251.18.83 - - [16/Jun/2016:20:05:05 +0000] "GET /config.js HTTP/1.1" 200 214 "http://entry.test.carre-project.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
proxy-1 | 2016-06-16T20:05:05.547591838Z nginx.1 | entry.test.carre-project.eu 212.251.18.83 - - [16/Jun/2016:20:05:05 +0000] "GET /styles/app-64e21ab698.css HTTP/1.1" 200 5465 "http://entry.test.carre-project.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
proxy-1 | 2016-06-16T20:05:05.571256586Z nginx.1 | entry.test.carre-project.eu 212.251.18.83 - - [16/Jun/2016:20:05:05 +0000] "GET /styles/vendor-8184b27656.css HTTP/1.1" 200 49146 "http://entry.test.carre-project.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
proxy-1 | 2016-06-16T20:05:05.628708156Z nginx.1 | entry.test.carre-project.eu 212.251.18.83 - - [16/Jun/2016:20:05:05 +0000] "GET /scripts/app-d02e74115a.js HTTP/1.1" 200 41442 "http://entry.test.carre-project.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
proxy-1 | 2016-06-16T20:05:05.848328843Z nginx.1 | entry.test.carre-project.eu 212.251.18.83 - - [16/Jun/2016:20:05:05 +0000] "GET /scripts/vendor-e868f00ec3.js HTTP/1.1" 200 464840 "http://entry.test.carre-project.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
proxy-1 | 2016-06-16T20:05:06.656756710Z nginx.1 | entry.test.carre-project.eu 212.251.18.83 - - [16/Jun/2016:20:05:06 +0000] "GET /fonts/fontawesome-webfont.woff2?v=4.4.0 HTTP/1.1" 200 64464 "http://entry.test.carre-project.eu/styles/vendor-8184b27656.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
proxy-1 | 2016-06-16T20:05:06.730425213Z nginx.1 | entry.test.carre-project.eu 212.251.18.83 - - [16/Jun/2016:20:05:06 +0000] "GET /assets/images/carre_logo.png HTTP/1.1" 200 3958 "http://entry.test.carre-project.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
proxy-1 | 2016-06-16T20:05:06.803201251Z nginx.1 | entry.test.carre-project.eu 212.251.18.83 - - [16/Jun/2016:20:05:06 +0000] "GET /assets/images/model.jpg HTTP/1.1" 200 222008 "http://entry.test.carre-project.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
proxy-1 | 2016-06-16T20:05:06.840664216Z nginx.1 | entry.test.carre-project.eu 212.251.18.83 - - [16/Jun/2016:20:05:06 +0000] "GET /api/carreapi/public_en_count_all/https%3A%2F%2Fcarre.kmi.open.ac.uk%2Fws%2Fquery/PREFIX%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%20%0APREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%20%0APREFIX%20carreUsers%3A%20%3Chttps%3A%2F%2Fcarre.kmi.open.ac.uk%2Fusers%2F%3E%20%0APREFIX%20risk%3A%20%3Chttp%3A%2F%2Fcarre.kmi.open.ac.uk%2Fontology%2Frisk.owl%23%3E%20%0APREFIX%20ME%3A%20%3Chttp%3A%2F%2Fcarre.kmi.open.ac.uk%2Fmeasurement_types%2F%3E%20%0APREFIX%20OB%3A%20%3Chttp%3A%2F%2Fcarre.kmi.open.ac.uk%2Fobservables%2F%3E%20%0APREFIX%20RL%3A%20%3Chttp%3A%2F%2Fcarre.kmi.open.ac.uk%2Frisk_elements%2F%3E%20%0APREFIX%20RV%3A%20%3Chttp%3A%2F%2Fcarre.kmi.open.ac.uk%2Frisk_evidences%2F%3E%20%0APREFIX%20RF%3A%20%3Chttp%3A%2F%2Fcarre.kmi.open.ac.uk%2Frisk_factors%2F%3E%20%0APREFIX%20RW%3A%20%3Chttp%3A%2F%2Fcarre.kmi.open.ac.uk%2Frisk_r
proxy-1 | 2016-06-16T20:05:07.158855011Z nginx.1 | entry.test.carre-project.eu 212.251.18.83 - - [16/Jun/2016:20:05:07 +0000] "GET /favicon.ico HTTP/1.1" 200 732 "http://entry.test.carre-project.eu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
proxy-1 | 2016-06-16T20:05:08.314884103Z nginx.1 | entry.test.carre-project.eu 66.133.109.36 - - [16/Jun/2016:20:05:08 +0000] "GET /.well-known/acme-challenge/Y3vYw3K_tZM9jWLXIu8_VqjJzeDnsRY1s3C76gut61c HTTP/1.1" 200 87 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
proxy-1 | 2016-06-16T20:05:13.114120993Z sslgen.1 | 2016/06/16 20:05:13 [/createSSL.sh]: IMPORTANT NOTES:
proxy-1 | 2016-06-16T20:05:13.114468824Z sslgen.1 | e a
proxy-1 | 2016-06-16T20:05:13.114726076Z sslgen.1 | rsion of this certificate in the future, simply run certbot-auto
proxy-1 | 2016-06-16T20:05:13.176715292Z sslgen.1 | 2016/06/16 20:05:13 Watching docker events
proxy-1 | 2016-06-16T20:05:13.207077203Z sslgen.1 | 2016/06/16 20:05:13 Contents of /createSSL.sh did not change. Skipping notification '/createSSL.sh'
proxy-1 | 2016-06-16T20:06:01.173913593Z nginx.1 | entry.test.carre-project.eu 212.251.18.83 - - [16/Jun/2016:20:06:01 +0000] "GET / HTTP/1.1" 301 185 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
proxy-1 | 2016-06-16T20:06:24.053291110Z nginx.1 | edu.test.carre-project.eu 212.251.18.83 - - [16/Jun/2016:20:06:24 +0000] "GET / HTTP/1.1" 301 185 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"

**Comment by evodicka** [comment]
I think your proxy container needs a port mapping of port 443, too, otherwise the https connections will not reach the proxy.

**Comment by portokallidis** [comment]
I added the port 443 but still no luck.
now the stack is: 

```
  edu:
    image: 'carre/educational-aggregator:latest'
    environment:
      - NODE_ENV=production
      - PORT=80
      - VIRTUAL_HOST=edu.test.carre-project.eu
    expose:
      - '80'
    restart: always
  entry:
    image: 'carre/risk-entry-system:latest'
    environment:
      - NODE_ENV=production
      - PORT=80
      - VIRTUAL_HOST=entry.test.carre-project.eu
    expose:
      - '80'
    restart: always
  proxy:
    image: 'eforce21/letsencrypt-nginx-proxy:latest'
    environment:
      - LETSENCRYPT_EMAIL=portokallidis@gmail.com
    links:
      - edu
      - entry
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
```
