### ISSUE TITLE
Cannot get it run... (at least the letsencrypt and ssl-proxy part not)

### ISSUE THREAD

**Issue by tkaefer** [eforce21/letsencrypt-nginx-proxy#5]
Hi,

I've been playing around with the whole thingy for some hours, but I am just able to have a http not no https proxy setup running.

I am doing this by a docker-compose file like this:

```
rproxy :
  image: eforce21/letsencrypt-nginx-proxy:1.0.2
  ports:
    - "{{IP}}:80:80"
    - "{{IP}}:443:443"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
  restart: always
  environment:
    - LETSENCRYPT_EMAIL=myown@email.address
wordpress:
  image: wordpress
  links:
    - mariadb:mysql
  volumes:
    - ./wordpress-data:/var/www/html
  environment:
    - VIRTUAL_HOST=blog.myhost.addrress
mariadb:
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD={{secret}}
  volumes:
    - ./mariadb-data:/var/lib/mysql
```

I would appreciate any hint - I am stuck here.
